### PR TITLE
Handle string shard key

### PR DESCRIPTION
**Pull request by if1live**
Usually, shard key is integer. but sometimes, shard key can be string.
I can't understand what happen inside library, but it happen. (shard_key=1234 is changed to shard_key="1234")
Maybe this code is cause. https://github.com/drecom/activerecord-turntable/blob/v2.1.1/lib/active_record/turntable/mixer.rb#L189
I modify code to handle shard_key="1234".

### CODE REVIEW

**Comment by gussan** [comment]
@if1live thank you for the PR. Would you tell me which activerecord version do you use?

**Comment by if1live** [comment]
activerecord (4.0.3)

**Comment by gussan** [comment]
@if1live I'm sorry for the delay in my response. Could you provide a reproducible example or backtraces?

**Comment by if1live** [comment]
Sorry. I can't make reproducible example. I didn't understand current project. I provide call stack.

## Code
I edit two code for logging.

### active_record/turntable/cluster.rb
```ruby
def shard_for(key)
  if key.is_a? String
    p key
    puts caller
    exit
  end
    @shards[@algorithm.calculate(key)]
  rescue
    raise ActiveRecord::Turntable::CannotSpecifyShardError,
      "cannot select_shard for key:#{key}"
end
```

### active_record/turntable/mixer.rb : line 189
```ruby
def build_update_fader(tree, method, query, *args, &block)
  shard_keys = find_shard_keys(tree.where, @proxy.klass.table_name, @proxy.klass.turntable_shard_key.to_s); puts "shard_keys : #{shard_keys}"
  shards_with_query = if shard_keys.present?
  ...
```

### Log
debug print message and call stack. I use current master branch.

```
shard_keys : [1321]
shard_keys : [1321]
shard_keys : ["1321"]
"1321"
__proj__/vendor/ruby/2.1.0/bundler/gems/activerecord-turntable-60ce80c1a12a/lib/active_record/turntable/mixer.rb:191:in `block in build_update_fader'
__proj__/vendor/ruby/2.1.0/bundler/gems/activerecord-turntable-60ce80c1a12a/lib/active_record/turntable/mixer.rb:191:in `map'
__proj__/vendor/ruby/2.1.0/bundler/gems/activerecord-turntable-60ce80c1a12a/lib/active_record/turntable/mixer.rb:191:in `build_update_fader'
__proj__/vendor/ruby/2.1.0/bundler/gems/activerecord-turntable-60ce80c1a12a/lib/active_record/turntable/mixer.rb:41:in `build_fader'
__proj__/vendor/ruby/2.1.0/bundler/gems/activerecord-turntable-60ce80c1a12a/lib/active_record/turntable/connection_proxy.rb:61:in `method_missing'
(eval):30:in `update_record'
__proj__/vendor/ruby/2.1.0/gems/activerecord-4.0.3/lib/active_record/attribute_methods/dirty.rb:74:in `update_record'
__proj__/vendor/ruby/2.1.0/gems/activerecord-4.0.3/lib/active_record/callbacks.rb:310:in `block in update_record'
__proj__/vendor/ruby/2.1.0/gems/activesupport-4.0.3/lib/active_support/callbacks.rb:373:in `_run__4067321378248301272__update__callbacks'
__proj__/vendor/ruby/2.1.0/gems/activesupport-4.0.3/lib/active_support/callbacks.rb:80:in `run_callbacks'
__proj__/vendor/ruby/2.1.0/gems/activerecord-4.0.3/lib/active_record/callbacks.rb:310:in `update_record'
__proj__/vendor/ruby/2.1.0/gems/activerecord-4.0.3/lib/active_record/timestamp.rb:70:in `update_record'
__proj__/vendor/ruby/2.1.0/gems/activerecord-4.0.3/lib/active_record/persistence.rb:477:in `create_or_update'
__proj__/vendor/ruby/2.1.0/gems/activerecord-4.0.3/lib/active_record/callbacks.rb:302:in `block in create_or_update'
__proj__/vendor/ruby/2.1.0/gems/activesupport-4.0.3/lib/active_support/callbacks.rb:403:in `_run__4067321378248301272__save__callbacks'
__proj__/vendor/ruby/2.1.0/gems/activesupport-4.0.3/lib/active_support/callbacks.rb:80:in `run_callbacks'
__proj__/vendor/ruby/2.1.0/gems/activerecord-4.0.3/lib/active_record/callbacks.rb:302:in `create_or_update'
__proj__/vendor/ruby/2.1.0/gems/activerecord-4.0.3/lib/active_record/persistence.rb:128:in `save!'
__proj__/vendor/ruby/2.1.0/gems/activerecord-4.0.3/lib/active_record/validations.rb:57:in `save!'
__proj__/vendor/ruby/2.1.0/gems/activerecord-4.0.3/lib/active_record/attribute_methods/dirty.rb:41:in `save!'
__proj__/vendor/ruby/2.1.0/gems/activerecord-4.0.3/lib/active_record/transactions.rb:275:in `block in save!'
__proj__/vendor/ruby/2.1.0/bundler/gems/activerecord-turntable-60ce80c1a12a/lib/active_record/turntable/active_record_ext/transactions.rb:15:in `block in with_transaction_returning_status'
__proj__/vendor/ruby/2.1.0/bundler/gems/activerecord-turntable-60ce80c1a12a/lib/active_record/turntable/cluster.rb:70:in `call'
__proj__/vendor/ruby/2.1.0/bundler/gems/activerecord-turntable-60ce80c1a12a/lib/active_record/turntable/cluster.rb:70:in `block in shards_transaction'
__proj__/vendor/ruby/2.1.0/gems/activerecord-4.0.3/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `block in transaction'
__proj__/vendor/ruby/2.1.0/gems/activerecord-4.0.3/lib/active_record/connection_adapters/abstract/database_statements.rb:210:in `within_new_transaction'
__proj__/vendor/ruby/2.1.0/gems/activerecord-4.0.3/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `transaction'
__proj__/vendor/ruby/2.1.0/bundler/gems/activerecord-turntable-60ce80c1a12a/lib/active_record/turntable/cluster.rb:69:in `shards_transaction'
__proj__/vendor/ruby/2.1.0/bundler/gems/activerecord-turntable-60ce80c1a12a/lib/active_record/turntable/connection_proxy.rb:22:in `shards_transaction'
__proj__/vendor/ruby/2.1.0/bundler/gems/activerecord-turntable-60ce80c1a12a/lib/active_record/turntable/active_record_ext/transactions.rb:12:in `with_transaction_returning_status'
__proj__/vendor/ruby/2.1.0/gems/activerecord-4.0.3/lib/active_record/transactions.rb:275:in `save!'
__proj__/spec/controllers/quest_continues_controller_spec.rb:58:in `block (4 levels) in <top (required)>'
__proj__/vendor/ruby/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:114:in `instance_eval'
__proj__/vendor/ruby/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:114:in `block in run'
__proj__/vendor/ruby/2.1.0/gems/rspec-rails-2.14.0/lib/rspec/rails/example/controller_example_group.rb:158:in `call'
__proj__/vendor/ruby/2.1.0/gems/rspec-rails-2.14.0/lib/rspec/rails/example/controller_example_group.rb:158:in `block (2 levels) in <module:ControllerExampleGroup>'
...rspec-rails...
```

**Comment by gussan** [comment]
I'm very sorry for delay, I found a reproducible environment.

Following environment:

1. Using `activerecord-turntable` with `activerecord-unsigned-column`
2. Tables with optimistic locking
3. `shard_key` column is `unsigned`
4. On update 

On this environment, shard_key is quoted as `string` column.

I think this behavior is not caused by activerecord-turntable,
So I wrote patch for `activerecord-unsigned-column`

https://github.com/gussan/activerecord-unsigned-column/commit/5328ef2017a81127473f28993bf43b34a38baf53

If you are using `activerecord-unsigned-column`, Could you try it?

**Comment by if1live** [comment]
Thanks. It works.

**Comment by if1live** [comment]
Sorry, but I notice that my bug is not resolved.
I use activerecord-unsigned-column.
But if bug occur, program flow doesn't enter inside activerecord-unsigned-column.


I found related commit. c1a2619 is worked. 0e2b6b5 is not worked.
https://github.com/drecom/activerecord-turntable/commit/0e2b6b55c121069ba8f7d1dd11e13fdab4c34259

on my environment, 

```
self.send(turntable_shard_key) 
=> 3139 (number)
```

```
self.class.quote_value(self.send(turntable_shard_key), column_for_attribute(klass.turntable_shard_key))
=> "3139" (string)
```

I think that those are causes.

1. locking_optimistic
2. use activerecord-unsigned-column and use unsigned column as shard key

**Comment by gussan** [comment]
This issue was not caused by activerecord-turntable and activerecord-unsigned-column gem is deprecated. So I close this PR. Thx.

**Pull request closed without merging**
